// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseColumnPreview } from "./DatabaseColumnPreview";

export type DatabaseTablePreview = { name: string, kind: string, columns: Array<DatabaseColumnPreview>, rows: Array<Array<string>>, rowCount: number | null, truncated: boolean, };
