// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugVariableInfo = { name: string, value: string, type_name: string | null, variables_reference: number, evaluate_name: string | null, named_variables: number | null, indexed_variables: number | null, };
