// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugStackFrame } from "./DebugStackFrame";
import type { DebugThreadInfo } from "./DebugThreadInfo";

export type DebugStackTrace = { session_id: string, thread: DebugThreadInfo, frames: Array<DebugStackFrame>, total_frames: number | null, };
