// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugResolvedBreakpoint = { id: number | null, path: string, line: number, column: number | null, verified: boolean, message: string | null, };
