// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugStackFrame = { id: number, name: string, source_path: string | null, line: number, column: number, };
