// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugSourceBreakpoint = { path: string, line: number, column: number | null, condition: string | null, log_message: string | null, };
