// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugAdapterStatus } from "./DebugAdapterStatus";

export type DebugAdapterInfo = { id: string, name: string, command: string, args: Array<string>, workspace_root: string, status: DebugAdapterStatus, error: string | null, };
