// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferId } from "./BufferId";
import type { FileViewDescriptor } from "./FileViewDescriptor";

export type DocumentSnapshot = { id: BufferId, path: string | null, title: string, language_id: string, text: string, view: FileViewDescriptor, version: number, is_dirty: boolean, is_untitled: boolean, opened_at: string, };
