// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionContributionPoint } from "./ExtensionContributionPoint";
import type { ExtensionStatus } from "./ExtensionStatus";

export type ExtensionInfo = { id: string, name: string, version: string, root: string, manifest_path: string, wasm_module: string, contributes: Array<string>, contribution_points: Array<ExtensionContributionPoint>, status: ExtensionStatus, error: string | null, };
