// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionCommandContribution } from "./ExtensionCommandContribution";
import type { ExtensionHostPermission } from "./ExtensionHostPermission";

export type ExtensionManifest = { id: string, name: string, version: string, wasm_module: string, permissions: Array<ExtensionHostPermission>, contributes: Array<string>, commands: Array<ExtensionCommandContribution>, };
