// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionCommandRoute = { id: string, title: string, category: string | null, handler: string, extension_id: string, extension_name: string, extension_version: string, };
