// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionActivated = { id: string, name: string, version: string, root: string, wasm_module: string, fuel_consumed: number, fuel_remaining: number, };
