// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileOpenMode } from "./FileOpenMode";
import type { FileViewCategory } from "./FileViewCategory";
import type { FileViewStrategy } from "./FileViewStrategy";

export type FileViewDescriptor = { category: FileViewCategory, strategy: FileViewStrategy, mode: FileOpenMode, displayName: string, mimeType: string | null, extensions: Array<string>, editable: boolean, previewable: boolean, aiReadable: boolean, binary: boolean, maxInlineBytes: bigint | null, notes: Array<string>, };
