// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileViewCategory = "text" | "code" | "markdown" | "config" | "data" | "spreadsheet" | "database" | "pdf" | "office" | "image" | "audio" | "video" | "archive" | "notebook" | "diagram" | "font" | "executable" | "binary" | "unknown";
