// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetadata } from "./FileMetadata";
import type { FilePreview } from "./FilePreview";
import type { FileViewDescriptor } from "./FileViewDescriptor";

export type FileInspection = { path: string, title: string, descriptor: FileViewDescriptor, metadata: FileMetadata, preview: FilePreview, aiContext: string, truncated: boolean, warnings: Array<string>, };
