// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileInspectionOptions = { maxTextBytes: number, maxRows: number, maxColumns: number, maxArchiveEntries: number, };