// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileViewStrategy = "monacoText" | "markdownPreview" | "tablePreview" | "spreadsheetPreview" | "spreadsheetEditor" | "tableEditor" | "databasePreview" | "databaseEditor" | "pdfPreview" | "officePreview" | "imagePreview" | "audioPreview" | "videoPreview" | "archivePreview" | "notebookPreview" | "diagramPreview" | "binaryPreview" | "externalOnly";
