// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitDiffFile } from "./GitDiffFile";

export type GitDiff = { files: Array<GitDiffFile>, additions: number, deletions: number, patch: string, truncated: boolean, };
