// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageServerStatus } from "./LanguageServerStatus";

export type LanguageServerInfo = { language_id: string, name: string, command: string, args: Array<string>, workspace_root: string, status: LanguageServerStatus, error: string | null, };
