// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspCompletionItemKind } from "./LspCompletionItemKind";
import type { LspInsertTextFormat } from "./LspInsertTextFormat";
import type { LspRange } from "./LspRange";

export type LspCompletionItem = { label: string, kind: LspCompletionItemKind | null, detail: string | null, documentation: string | null, insert_text: string, insert_text_format: LspInsertTextFormat, filter_text: string | null, sort_text: string | null, range: LspRange | null, commit_characters: Array<string>, preselect: boolean, };
