// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspInlayHintKind } from "./LspInlayHintKind";

export type LspInlayHint = { label: string, tooltip: string | null, line: number, column: number, kind: LspInlayHintKind | null, padding_left: boolean, padding_right: boolean, };
