// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspSignatureParameter } from "./LspSignatureParameter";

export type LspSignatureInformation = { label: string, documentation: string | null, parameters: Array<LspSignatureParameter>, active_parameter: number | null, };
