// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspTextEdit } from "./LspTextEdit";

export type LspWorkspaceEditFile = { path: string, edits: Array<LspTextEdit>, };
