// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentEditResult } from "./DocumentEditResult";
import type { DocumentSnapshot } from "./DocumentSnapshot";
import type { GitStatus } from "./GitStatus";
import type { WorkspaceDiagnostic } from "./WorkspaceDiagnostic";
import type { WorkspaceInfo } from "./WorkspaceInfo";

export type LuxEvent = { "type": "workspaceChanged", workspace: WorkspaceInfo | null, } | { "type": "fsChanged", path: string, } | { "type": "editorDocumentClosed", document: DocumentSnapshot, } | { "type": "editorDocumentChanged", document: DocumentSnapshot, } | { "type": "editorDocumentsChanged", documents: Array<DocumentSnapshot>, } | { "type": "editorDocumentEdited", document: DocumentEditResult, } | { "type": "editorDiagnosticsChanged", path: string, diagnostics: Array<WorkspaceDiagnostic>, } | { "type": "searchProgress", query: string, indexed_files: number, } | { "type": "terminalOutput", session_id: string, data: string, } | { "type": "gitStatusChanged", status: GitStatus, } | { "type": "settingsChanged", key: string, };
