// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotebookCellPreview = { index: number, cellType: string, text: string, outputText: string, };
