// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchOptions = { case_sensitive: boolean, whole_word: boolean, use_regex: boolean, include_hidden: boolean, include_globs: Array<string>, exclude_globs: Array<string>, max_results: number, };
