// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";

export type WorkspaceInfo = { id: WorkspaceId, name: string, root: string, opened_at: string, };
