import {
  Binary,
  Braces,
  Database,
  File,
  FileArchive,
  FileBraces,
  FileCode,
  FileCog,
  FileImage,
  FileKey,
  FileLock,
  FileSpreadsheet,
  FileTerminal,
  FileText,
  FileType,
  Globe,
  Hash,
  Image,
  Music,
  Package,
  Palette,
  Video,
  type LucideIcon,
} from "lucide-react";

export type FileIconMeta = {
  Icon: LucideIcon;
  className: string;
};

const exactIconMap = new Map<string, FileIconMeta>([
  [".env", icon(FileLock, "env")],
  [".env.local", icon(FileLock, "env")],
  [".gitignore", icon(Hash, "git")],
  [".gitattributes", icon(Hash, "git")],
  [".gitmodules", icon(Hash, "git")],
  [".npmrc", icon(Package, "package")],
  [".prettierrc", icon(FileCog, "config")],
  [".prettierignore", icon(FileCog, "config")],
  [".eslintrc", icon(FileCog, "config")],
  [".eslintrc.js", icon(FileCog, "javascript")],
  [".eslintrc.cjs", icon(FileCog, "javascript")],
  [".eslintrc.json", icon(FileBraces, "json")],
  [".yarnrc", icon(Package, "package")],
  ["bun.lockb", icon(FileLock, "lock")],
  ["compose.yaml", icon(Package, "docker")],
  ["compose.yml", icon(Package, "docker")],
  ["dockerfile", icon(Package, "docker")],
  ["docker-compose.yaml", icon(Package, "docker")],
  ["docker-compose.yml", icon(Package, "docker")],
  ["makefile", icon(FileCog, "config")],
  ["cargo.toml", icon(Package, "rust")],
  ["cargo.lock", icon(FileLock, "lock")],
  ["go.mod", icon(Package, "go")],
  ["go.sum", icon(FileLock, "lock")],
  ["package.json", icon(Package, "package")],
  ["package-lock.json", icon(FileLock, "lock")],
  ["pnpm-lock.yaml", icon(FileLock, "lock")],
  ["yarn.lock", icon(FileLock, "lock")],
  ["deno.json", icon(FileCog, "typescript")],
  ["deno.jsonc", icon(FileCog, "typescript")],
  ["tsconfig.json", icon(FileCog, "typescript")],
  ["jsconfig.json", icon(FileCog, "javascript")],
  ["next.config.js", icon(FileCog, "javascript")],
  ["next.config.mjs", icon(FileCog, "javascript")],
  ["next.config.ts", icon(FileCog, "typescript")],
  ["vite.config.ts", icon(FileCog, "config")],
  ["vite.config.js", icon(FileCog, "config")],
  ["vitest.config.ts", icon(FileCog, "config")],
  ["vitest.config.js", icon(FileCog, "config")],
]);

const extensionIconMap = new Map<string, FileIconMeta>([
  ["rs", icon(FileCode, "rust")],
  ["toml", icon(FileCog, "config")],
  ["ron", icon(FileCog, "config")],
  ["lock", icon(FileLock, "lock")],
  ["ts", icon(FileCode, "typescript")],
  ["tsx", icon(FileCode, "typescript")],
  ["mts", icon(FileCode, "typescript")],
  ["cts", icon(FileCode, "typescript")],
  ["d.ts", icon(FileCode, "typescript")],
  ["js", icon(FileCode, "javascript")],
  ["jsx", icon(FileCode, "javascript")],
  ["mjs", icon(FileCode, "javascript")],
  ["cjs", icon(FileCode, "javascript")],
  ["json", icon(FileBraces, "json")],
  ["jsonc", icon(FileBraces, "json")],
  ["html", icon(Globe, "html")],
  ["htm", icon(Globe, "html")],
  ["css", icon(Palette, "css")],
  ["scss", icon(Palette, "css")],
  ["sass", icon(Palette, "css")],
  ["less", icon(Palette, "css")],
  ["md", icon(FileText, "markdown")],
  ["mdx", icon(FileText, "markdown")],
  ["txt", icon(FileText, "text")],
  ["rtf", icon(FileText, "document")],
  ["log", icon(FileText, "text")],
  ["ini", icon(FileCog, "config")],
  ["conf", icon(FileCog, "config")],
  ["config", icon(FileCog, "config")],
  ["yml", icon(FileCog, "yaml")],
  ["yaml", icon(FileCog, "yaml")],
  ["xml", icon(FileCode, "xml")],
  ["vue", icon(FileCode, "vue")],
  ["svelte", icon(FileCode, "svelte")],
  ["svg", icon(FileImage, "image")],
  ["png", icon(Image, "image")],
  ["jpg", icon(Image, "image")],
  ["jpeg", icon(Image, "image")],
  ["webp", icon(Image, "image")],
  ["gif", icon(Image, "image")],
  ["ico", icon(Image, "image")],
  ["avif", icon(Image, "image")],
  ["bmp", icon(Image, "image")],
  ["tiff", icon(Image, "image")],
  ["ttf", icon(FileType, "font")],
  ["otf", icon(FileType, "font")],
  ["woff", icon(FileType, "font")],
  ["woff2", icon(FileType, "font")],
  ["mp3", icon(Music, "audio")],
  ["wav", icon(Music, "audio")],
  ["flac", icon(Music, "audio")],
  ["ogg", icon(Music, "audio")],
  ["mp4", icon(Video, "video")],
  ["webm", icon(Video, "video")],
  ["mov", icon(Video, "video")],
  ["mkv", icon(Video, "video")],
  ["zip", icon(FileArchive, "archive")],
  ["rar", icon(FileArchive, "archive")],
  ["7z", icon(FileArchive, "archive")],
  ["tar", icon(FileArchive, "archive")],
  ["gz", icon(FileArchive, "archive")],
  ["tgz", icon(FileArchive, "archive")],
  ["pdf", icon(FileType, "pdf")],
  ["doc", icon(FileText, "document")],
  ["docx", icon(FileText, "document")],
  ["xls", icon(FileSpreadsheet, "spreadsheet")],
  ["xlsx", icon(FileSpreadsheet, "spreadsheet")],
  ["csv", icon(FileSpreadsheet, "spreadsheet")],
  ["db", icon(Database, "database")],
  ["sqlite", icon(Database, "database")],
  ["sql", icon(Database, "database")],
  ["sqlite3", icon(Database, "database")],
  ["duckdb", icon(Database, "database")],
  ["sh", icon(FileTerminal, "shell")],
  ["bash", icon(FileTerminal, "shell")],
  ["zsh", icon(FileTerminal, "shell")],
  ["ps1", icon(FileTerminal, "shell")],
  ["bat", icon(FileTerminal, "shell")],
  ["cmd", icon(FileTerminal, "shell")],
  ["py", icon(FileCode, "python")],
  ["pyw", icon(FileCode, "python")],
  ["ipynb", icon(FileCode, "python")],
  ["go", icon(FileCode, "go")],
  ["java", icon(FileCode, "java")],
  ["kt", icon(FileCode, "kotlin")],
  ["kts", icon(FileCode, "kotlin")],
  ["c", icon(FileCode, "c")],
  ["h", icon(FileCode, "c")],
  ["cpp", icon(FileCode, "cpp")],
  ["cc", icon(FileCode, "cpp")],
  ["cxx", icon(FileCode, "cpp")],
  ["hpp", icon(FileCode, "cpp")],
  ["hh", icon(FileCode, "cpp")],
  ["hxx", icon(FileCode, "cpp")],
  ["cs", icon(FileCode, "csharp")],
  ["fs", icon(FileCode, "fsharp")],
  ["fsx", icon(FileCode, "fsharp")],
  ["php", icon(FileCode, "php")],
  ["rb", icon(FileCode, "ruby")],
  ["lua", icon(FileCode, "lua")],
  ["swift", icon(FileCode, "swift")],
  ["scala", icon(FileCode, "scala")],
  ["dart", icon(FileCode, "dart")],
  ["ex", icon(FileCode, "elixir")],
  ["exs", icon(FileCode, "elixir")],
  ["erl", icon(FileCode, "erlang")],
  ["hrl", icon(FileCode, "erlang")],
  ["zig", icon(FileCode, "zig")],
  ["nim", icon(FileCode, "nim")],
  ["r", icon(FileCode, "r")],
  ["jl", icon(FileCode, "julia")],
  ["hs", icon(FileCode, "haskell")],
  ["lhs", icon(FileCode, "haskell")],
  ["wasm", icon(Binary, "binary")],
  ["exe", icon(Binary, "binary")],
  ["dll", icon(Binary, "binary")],
  ["bin", icon(Binary, "binary")],
  ["pem", icon(FileKey, "key")],
  ["key", icon(FileKey, "key")],
  ["crt", icon(FileKey, "key")],
]);

export function fileIconForName(name: string): FileIconMeta {
  const lowerName = name.toLowerCase();
  const exact = exactIconMap.get(lowerName);
  if (exact) return exact;

  const extension = longestExtension(lowerName);
  return extensionIconMap.get(extension) ?? icon(File, "default");
}

function longestExtension(lowerName: string) {
  const parts = lowerName.split(".").filter(Boolean);
  if (parts.length <= 1) return "";
  for (let index = 0; index < parts.length - 1; index += 1) {
    const extension = parts.slice(index).join(".");
    if (extensionIconMap.has(extension)) return extension;
  }
  return parts.at(-1) ?? "";
}

function icon(Icon: LucideIcon, tone: string): FileIconMeta {
  return { Icon, className: `file-icon file-icon-${tone}` };
}
