export const LANGUAGE_LABELS: Record<string, string> = {
  rs: "Rust",
  ts: "TypeScript",
  tsx: "TypeScript",
  mts: "TypeScript",
  cts: "TypeScript",
  "d.ts": "TypeScript",
  js: "JavaScript",
  jsx: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  py: "Python",
  pyw: "Python",
  ipynb: "Notebook",
  go: "Go",
  java: "Java",
  kt: "Kotlin",
  kts: "Kotlin",
  c: "C",
  h: "C",
  cpp: "C++",
  cc: "C++",
  cxx: "C++",
  hpp: "C++",
  hh: "C++",
  hxx: "C++",
  cs: "C#",
  fs: "F#",
  fsx: "F#",
  php: "PHP",
  rb: "Ruby",
  lua: "Lua",
  luau: "Luau",
  swift: "Swift",
  scala: "Scala",
  dart: "Dart",
  ex: "Elixir",
  exs: "Elixir",
  erl: "Erlang",
  hrl: "Erlang",
  zig: "Zig",
  nim: "Nim",
  r: "R",
  jl: "Julia",
  hs: "Haskell",
  lhs: "Haskell",
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",
  kotlin: "Kotlin",

  // Web
  html: "HTML",
  htm: "HTML",
  css: "CSS",
  scss: "SCSS",
  sass: "Sass",
  less: "Less",
  svg: "SVG",
  xml: "XML",
  yaml: "YAML",
  yml: "YAML",
  json: "JSON",
  jsonc: "JSONC",
  mdx: "MDX",
  md: "Markdown",
  rtf: "RTF",
  txt: "TXT",
  log: "Log",
  csv: "CSV",

  // Config / data
  toml: "TOML",
  ron: "RON",
  ini: "INI",
  conf: "Config",
  config: "Config",
  lock: "Lock",
  pdf: "PDF",
  sql: "SQL",
  sqlite: "SQLite",
  sqlite3: "SQLite3",
  db: "Database",
  duckdb: "DuckDB",
  proto: "Protobuf",
  prisma: "Prisma",
  gradle: "Gradle",
  sbt: "SBT",
  drawio: "DrawIO",
  tex: "LaTeX",
  patch: "Patch",

  // Shell / scripting
  sh: "Shell",
  bash: "Bash",
  zsh: "Zsh",
  ps1: "PowerShell",
  bat: "Batch",
  cmd: "CMD",

  // Images
  png: "PNG",
  jpg: "JPEG",
  jpeg: "JPEG",
  webp: "WebP",
  gif: "GIF",
  ico: "ICO",
  icns: "Icns",
  avif: "AVIF",
  bmp: "BMP",
  tiff: "TIFF",

  // Audio / video
  mp3: "MP3",
  wav: "WAV",
  flac: "FLAC",
  ogg: "OGG",
  mp4: "MP4",
  webm: "WebM",
  mov: "MOV",
  mkv: "MKV",

  // Fonts
  ttf: "TTF",
  otf: "OTF",
  woff: "WOFF",
  woff2: "WOFF2",

  // Archives
  zip: "ZIP",
  rar: "RAR",
  "7z": "7z",
  tar: "TAR",
  gz: "GZ",
  tgz: "TGZ",

  // Binary / certs
  wasm: "WASM",
  exe: "EXE",
  dll: "DLL",
  bin: "Binary",
  pem: "PEM",
  key: "Key",
  crt: "CRT",

  // Languages from extensionIconMap (no SVG icon)
  coffee: "CoffeeScript",
  clj: "Clojure",
  cljs: "ClojureScript",
  edn: "EDN",
  erb: "ERB",
  elm: "Elm",
  graphql: "GraphQL",
  gql: "GraphQL",
  pug: "Pug",
  haml: "Haml",
  slim: "Slim",
  styl: "Stylus",
  fortran: "Fortran",
  f: "Fortran",
  f90: "Fortran",
  ocaml: "OCaml",
  ml: "OCaml",
  res: "ReScript",
  resi: "ReScript",
  gleam: "Gleam",
  crystal: "Crystal",
  sol: "Solidity",
  http: "HTTP",
  rst: "reStructuredText",
  makefile: "Makefile",
  dockerfile: "Dockerfile",
  v: "V",
  razor: "Razor",
  pkl: "Pkl",
  svx: "SVX",
  twig: "Twig",
  liquid: "Liquid",
  njk: "Nunjucks",
  nunjucks: "Nunjucks",

  // Other / unknown
  scm: "Scheme",
  rev: "Rev",
  sample: "Sample",
  other: "Other",
  default: "File",
};

export function displayNameForLanguage(langId: string): string {
  return LANGUAGE_LABELS[langId.toLowerCase()] ?? pascalCase(langId);
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
