// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugConfigurationRequest } from "./DebugConfigurationRequest";

export type DebugConfiguration = { name: string, type: string, request: DebugConfigurationRequest, raw: Record<string, unknown>, };
