// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugAdapterInfo } from "./DebugAdapterInfo";
import type { DebugConfiguration } from "./DebugConfiguration";

export type DebugWorkspaceInfo = { adapters: Array<DebugAdapterInfo>, configurations: Array<DebugConfiguration>, launch_json_path: string | null, };
