// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugEvaluateResult = { session_id: string, expression: string, result: string, type_name: string | null, variables_reference: number, named_variables: number | null, indexed_variables: number | null, memory_reference: string | null, };
