// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugResolvedBreakpoint } from "./DebugResolvedBreakpoint";

export type DebugBreakpointsUpdate = { session_id: string, path: string, breakpoints: Array<DebugResolvedBreakpoint>, };
