// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugScopeInfo } from "./DebugScopeInfo";

export type DebugFrameScopes = { session_id: string, frame_id: number, scopes: Array<DebugScopeInfo>, };
