// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugSessionStatus = "starting" | "running" | "paused" | "stopping" | "stopped" | "error";
