// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugVariableInfo } from "./DebugVariableInfo";

export type DebugVariables = { session_id: string, variables_reference: number, variables: Array<DebugVariableInfo>, };
