// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionStatus } from "./DebugSessionStatus";

export type DebugSessionInfo = { id: string, configuration_name: string, adapter_id: string, adapter_name: string, workspace_root: string, status: DebugSessionStatus, started_at: string, stopped_at: string | null, active_thread_id: number | null, last_event: string | null, error: string | null, };
