// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferId } from "./BufferId";

export type DocumentEditResult = { id: BufferId, path: string | null, title: string, version: number, is_dirty: boolean, is_untitled: boolean, };
