// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionContributionKind } from "./ExtensionContributionKind";

export type ExtensionContributionPoint = { id: string, kind: ExtensionContributionKind, };
