// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionActivationReport } from "./ExtensionActivationReport";
import type { ExtensionContributionRegistration } from "./ExtensionContributionRegistration";
import type { ExtensionContributionUnavailable } from "./ExtensionContributionUnavailable";

export type ExtensionContributionRegistry = { activation: ExtensionActivationReport, registered: Array<ExtensionContributionRegistration>, unavailable: Array<ExtensionContributionUnavailable>, };
