// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionHostLimits = { max_memory_pages: number, activation_timeout_ms: number, max_output_bytes: number, };
