// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionCommandExecutionPhase } from "./ExtensionCommandExecutionPhase";
import type { ExtensionCommandExecutionStatus } from "./ExtensionCommandExecutionStatus";
import type { ExtensionCommandRoute } from "./ExtensionCommandRoute";

export type ExtensionCommandExecution = { command_id: string, route: ExtensionCommandRoute | null, status: ExtensionCommandExecutionStatus, phase: ExtensionCommandExecutionPhase, reason: string | null, duration_ms: number, activation_fuel_consumed: number | null, activation_fuel_remaining: number | null, handler_fuel_consumed: number | null, handler_fuel_remaining: number | null, };
