// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionWasmImport } from "./ExtensionWasmImport";

export type ExtensionWasmAbi = { version: number, entrypoint: string, required_exports: Array<string>, optional_exports: Array<string>, imports: Array<ExtensionWasmImport>, exports_memory: boolean, };
