// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionContributionPoint } from "./ExtensionContributionPoint";

export type ExtensionContributionRegistration = { extension_id: string, extension_name: string, extension_version: string, contribution: ExtensionContributionPoint, };
