// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionActivationBlocked } from "./ExtensionActivationBlocked";
import type { ExtensionActivationCandidate } from "./ExtensionActivationCandidate";

export type ExtensionActivationPlan = { candidates: Array<ExtensionActivationCandidate>, blocked: Array<ExtensionActivationBlocked>, };
