// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionCommandContribution } from "./ExtensionCommandContribution";
import type { ExtensionContributionPoint } from "./ExtensionContributionPoint";
import type { ExtensionHostActivationContract } from "./ExtensionHostActivationContract";
import type { ExtensionWasmPreflight } from "./ExtensionWasmPreflight";

export type ExtensionActivationCandidate = { id: string, name: string, version: string, root: string, manifest_path: string, wasm_module: string, contribution_points: Array<ExtensionContributionPoint>, commands: Array<ExtensionCommandContribution>, wasm_preflight: ExtensionWasmPreflight, host_contract: ExtensionHostActivationContract, };
