// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionContributionKind = "commands" | "themes" | "keybindings" | "languages" | "grammars" | "snippets" | "views" | "menus" | "settings" | "debuggers" | "tasks" | "problemMatchers" | "unknown";
