// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionActivated } from "./ExtensionActivated";
import type { ExtensionActivationFailed } from "./ExtensionActivationFailed";
import type { ExtensionActivationPlan } from "./ExtensionActivationPlan";

export type ExtensionActivationReport = { plan: ExtensionActivationPlan, activated: Array<ExtensionActivated>, failed: Array<ExtensionActivationFailed>, };
