// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionWasmImportKind } from "./ExtensionWasmImportKind";

export type ExtensionWasmImport = { module: string, name: string, kind: ExtensionWasmImportKind, };
