// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionHostLimits } from "./ExtensionHostLimits";
import type { ExtensionHostPermission } from "./ExtensionHostPermission";
import type { ExtensionWasmAbi } from "./ExtensionWasmAbi";

export type ExtensionHostActivationContract = { abi: ExtensionWasmAbi, permissions: Array<ExtensionHostPermission>, limits: ExtensionHostLimits, };
