// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitDiffFile = { path: string, old_path: string | null, status: string, additions: number, deletions: number, binary: boolean, };
