// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Keybinding } from "./Keybinding";

export type KeybindingProfile = { id: string, name: string, bindings: Array<Keybinding>, };
