// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspWorkspaceEdit } from "./LspWorkspaceEdit";

export type LspCodeAction = { title: string, kind: string | null, is_preferred: boolean, disabled_reason: string | null, edit: LspWorkspaceEdit | null, };
