// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";
import type { LspRange } from "./LspRange";

export type LspCodeActionDiagnostic = { range: LspRange, severity: DiagnosticSeverity | null, source: string | null, message: string, };
