// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspCompletionItem } from "./LspCompletionItem";

export type LspCompletionList = { is_incomplete: boolean, items: Array<LspCompletionItem>, };
