// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspFoldingRangeKind } from "./LspFoldingRangeKind";

export type LspFoldingRange = { start_line: number, end_line: number, start_column: number | null, end_column: number | null, kind: LspFoldingRangeKind | null, };
