// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspRange } from "./LspRange";

export type LspHover = { contents: Array<string>, range: LspRange | null, };
