// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspSignatureInformation } from "./LspSignatureInformation";

export type LspSignatureHelp = { signatures: Array<LspSignatureInformation>, active_signature: number | null, active_parameter: number | null, };
