// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspLocation } from "./LspLocation";
import type { LspSymbolKind } from "./LspSymbolKind";

export type LspWorkspaceSymbol = { name: string, kind: LspSymbolKind, location: LspLocation, container_name: string | null, };
