// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchHit = { path: string, line: number, column: number, match_length: number, match_text: string, preview: string, preview_match_start: number, preview_match_length: number, };
