// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";

export type SearchResponse = { query: string, hits: Array<SearchHit>, truncated: boolean, elapsed_ms: number, };
