// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextEdit = { start_line: number, start_column: number, end_line: number, end_column: number, text: string, };
