// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSnapshot } from "./DocumentSnapshot";

export type WorkspaceEditResult = { edited_documents: Array<DocumentSnapshot>, changed_paths: Array<string>, };
