export const FILE_ICONS_BASE = "/icons";

const extToSvg: Record<string, string> = {
  rs: "rust",
  ts: "ts",
  tsx: "react-ts",
  mts: "ts",
  cts: "ts",
  "d.ts": "dts",
  js: "js",
  jsx: "react",
  mjs: "js",
  cjs: "js",
  py: "python",
  pyw: "python",
  ipynb: "notebook",
  go: "go",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  c: "c",
  h: "h",
  cpp: "cplus",
  cc: "cplus",
  cxx: "cplus",
  hpp: "cplus",
  hh: "cplus",
  hxx: "cplus",
  cs: "csharp",
  fs: "fsharp",
  fsx: "fsharp",
  php: "php",
  rb: "ruby",
  lua: "lua",
  luau: "luau",
  swift: "swift",
  scala: "scala",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hrl: "erlang",
  zig: "zig",
  nim: "nim",
  r: "r",
  jl: "julia",
  hs: "haskell",
  lhs: "haskell",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  json: "brackets-orange",
  jsonc: "brackets-orange",
  md: "markdown",
  mdx: "mdx",
  css: "brackets-sky",
  scss: "sass",
  sass: "sass",
  less: "stylus",
  html: "code-blue",
  htm: "code-blue",
  svg: "svg",
  png: "image",
  jpg: "image",
  jpeg: "image",
  webp: "image",
  gif: "gif",
  ico: "image",
  avif: "image",
  bmp: "image",
  tiff: "image",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  toml: "gear",
  lock: "lock",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  ps1: "shell",
  bat: "shell",
  cmd: "shell",
  pdf: "pdf",
  csv: "csv",
  db: "database",
  sqlite: "database",
  sql: "database",
  sqlite3: "database",
  zip: "gear",
  rar: "gear",
  "7z": "gear",
  tar: "gear",
  gz: "gear",
  tgz: "gear",
  mp3: "audio",
  wav: "audio",
  flac: "audio",
  ogg: "audio",
  mp4: "video",
  webm: "video",
  mov: "video",
  mkv: "video",
  ttf: "font",
  otf: "font",
  woff: "font",
  woff2: "font",
  wasm: "assembly",
  exe: "exe",
  dll: "exe",
  bin: "gear",
  pem: "lock",
  key: "lock",
  crt: "lock",
  prisma: "prisma",
  gradle: "gradle",
  drawio: "drawio",
  proto: "proto",
  tex: "tex",
  patch: "patch",
  sbt: "sbt",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  coffee: "coffeescript",
  pl: "perl",
  pm: "perl",
  cmake: "cmake",
  d: "d",
  v: "v",
  razor: "razor",
  pkl: "pkl",
  svx: "svx",
  twig: "twig",
  liquid: "liquid",
  njk: "nunjucks",
  nunjucks: "nunjucks",
  pug: "pug",
  haml: "haml",
  fortran: "fortran",
  f: "fortran",
  f90: "fortran",
  ocaml: "ocaml",
  ml: "ocaml",
  res: "rescript",
  resi: "rescript-interface",
  gleam: "gleam",
  crystal: "crystal",
  sol: "solidity",
  http: "http",
  rst: "document",
  dockerfile: "docker",
};

const exactFileToSvg: Record<string, string> = {
  dockerfile: "docker",
  makefile: "gear",
  "cargo.toml": "gear",
  "cargo.lock": "lock",
  "go.mod": "go",
  "go.sum": "lock",
  "package.json": "node",
  "package-lock.json": "lock",
  "pnpm-lock.yaml": "lock",
  "bun.lockb": "bun",
  "yarn.lock": "yarn",
  "deno.json": "deno",
  "deno.jsonc": "deno",
  "tsconfig.json": "tsconfig",
  "jsconfig.json": "gear",
  "next.config.js": "next",
  "next.config.mjs": "next",
  "next.config.ts": "next",
  "vite.config.ts": "vite",
  "vite.config.js": "vite",
  "vite.config.mjs": "vite",
  "vitest.config.ts": "vitest",
  "vitest.config.js": "vitest",
  ".eslintrc": "eslint",
  ".eslintrc.js": "eslint",
  ".eslintrc.cjs": "eslint",
  ".eslintrc.json": "eslint",
  ".eslintrc.yaml": "eslint",
  ".eslintrc.yml": "eslint",
  ".prettierrc": "prettier",
  ".prettierrc.json": "prettier",
  ".prettierignore": "prettier",
  ".gitignore": "git",
  ".gitattributes": "git",
  ".gitmodules": "git",
  ".npmrc": "npm",
  ".yarnrc": "yarn",
  ".yarnrc.yml": "yarn",
  ".editorconfig": "editorconfig",
  ".babelrc": "babel",
  "babel.config.js": "babel",
  "babel.config.cjs": "babel",
  ".browserslistrc": "gear",
  "compose.yaml": "docker",
  "compose.yml": "docker",
  "docker-compose.yaml": "docker",
  "docker-compose.yml": "docker",
  "biome.json": "biome",
  "biome.jsonc": "biome",
  "oxlintrc.json": "oxlint",
  ".oxlintrc.json": "oxlint",
  "knip.json": "knip",
  ".knip.json": "knip",
  "turbo.json": "turborepo",
  "nx.json": "nx",
};

const fileIconCache = new Map<string, string | null>();

export function getFileIconSvg(name: string): string | null {
  const lower = name.toLowerCase();
  const cached = fileIconCache.get(lower);
  if (cached !== undefined) return cached;

  const exact = exactFileToSvg[lower];
  if (exact) {
    const path = `${FILE_ICONS_BASE}/files/${exact}.svg`;
    fileIconCache.set(lower, path);
    return path;
  }

  const ext = longestSvgExt(lower);
  if (ext) {
    const base = extToSvg[ext];
    if (base) {
      const path = `${FILE_ICONS_BASE}/files/${base}.svg`;
      fileIconCache.set(lower, path);
      return path;
    }
  }

  fileIconCache.set(lower, null);
  return null;
}

function longestSvgExt(lowerName: string): string | null {
  const parts = lowerName.split(".").filter(Boolean);
  if (parts.length <= 1) return null;
  for (let i = 0; i < parts.length - 1; i++) {
    const ext = parts.slice(i).join(".");
    if (extToSvg[ext]) return ext;
  }
  return parts.at(-1) ?? null;
}

const folderNameToSvg: Record<string, string> = {
  src: "src",
  app: "app",
  public: "images",
  assets: "assets",
  images: "images",
  img: "images",
  fonts: "fonts",
  styles: "sass",
  css: "sass",
  scss: "sass",
  sass: "sass",
  hooks: "hooks",
  utils: "utils",
  util: "utils",
  helpers: "helpers",
  help: "helpers",
  lib: "shared",
  config: "config",
  cfg: "config",
  constants: "constants",
  const: "constants",
  types: "interfaces",
  typings: "interfaces",
  interfaces: "interfaces",
  services: "services",
  providers: "providers",
  provider: "providers",
  middleware: "middleware",
  models: "models",
  model: "models",
  reducers: "reducer",
  reducer: "reducer",
  actions: "actions",
  effects: "effects",
  selectors: "selector",
  selector: "selector",
  routes: "router",
  router: "router",
  layout: "layout",
  layouts: "layout",
  i18n: "i18n",
  locale: "i18n",
  locales: "i18n",
  docs: "documents",
  doc: "documents",
  documents: "documents",
  build: "build",
  dist: "target",
  target: "target",
  out: "target",
  node_modules: "node-modules",
  database: "database",
  db: "database",
  docker: "docker",
  graphql: "graphql",
  prisma: "prisma",
  drizzle: "drizzle",
  mongo: "mongo",
  mongodb: "mongo",
  redis: "redis",
  core: "core",
  context: "context",
  modules: "modules",
  module: "modules",
  shared: "shared",
  pipes: "pipes",
  pipe: "pipes",
  facades: "facade",
  facade: "facade",
  interceptors: "interceptors",
  interceptor: "interceptors",
  components: "blue",
  component: "blue",
  widgets: "blue",
  features: "blue",
  screens: "blue",
  views: "blue",
  ui: "blue",
  github: "github",
  gitlab: "gitlab",
  workflows: "github",
  vercel: "vercel",
  aws: "aws",
  azure: "azure",
  firebase: "firebase",
  supabase: "supabase",
  tauri: "tauri",
  vscode: "vscode",
  ".vscode": "vscode",
  android: "android",
  ios: "ios",
  expo: "expo",
  bruno: "bruno",
  claude: "claude",
  cursor: "cursor",
  mail: "mail",
  emails: "mail",
  lock: "lock",
  nginx: "nginx",
  cypress: "cypress",
  e2e: "cypress",
  tests: "green",
  __tests__: "green",
  test: "green",
  spec: "green",
  specs: "green",
  mocks: "gray",
  mock: "gray",
  fixtures: "gray",
  fixture: "gray",
  api: "vercel",
  pages: "next",
  scripts: "utils",
  server: "serverless",
  functions: "serverless",
  lambda: "serverless",
  infra: "pulumi",
  infrastructure: "pulumi",
  migrations: "database",
  seeds: "database",
  seed: "database",
  bin: "utils",
  certificates: "lock",
  certs: "lock",
  keys: "lock",
  env: "lock",
  environments: "lock",
};

const folderIconCache = new Map<string, string>();

export function getFolderIconSvg(folderName: string, _expanded?: boolean): string {
  const lower = folderName.toLowerCase().replace(/^\.+/, "");
  const cached = folderIconCache.get(lower);
  if (cached) return cached;

  const base = folderNameToSvg[lower];
  const path = base
    ? `${FILE_ICONS_BASE}/folders/folder-${base}.svg`
    : `${FILE_ICONS_BASE}/folders/folder.svg`;
  folderIconCache.set(lower, path);
  return path;
}
